added optional progress bars for downloading (fetch function)
markovmodel/mdshare pull request #10
Opened 2018-07-11 17:03 UTC by marscher

fixes #9

2018-07-12 07:54 UTC, cwehmeyer requested changes

2018-07-12 07:54 UTC, cwehmeyer commented on mdshare/mdshare.py
> +            path = os.path.join(working_directory, f)
This line fails when testing on my OSX machine:

```Python-Traceback
_________________________________________________________________________________________ test_fetch_npz_file_temp _________________________________________________________________________________________

    def test_fetch_npz_file_temp():
>       files = fetch('mdshare-test-??.txt', working_directory=None)

mdshare/test/test_mdshare.py:59: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
mdshare/mdshare.py:186: in fetch
    path = os.path.join(working_directory, f)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

a = None, p = ('mdshare-test-00.txt',)

    def join(a, *p):
        """Join two or more pathname components, inserting '/' as needed.
        If any component is an absolute path, all previous path components
        will be discarded.  An empty last part will result in a path that
        ends with a separator."""
>       a = os.fspath(a)
E       TypeError: expected str, bytes or os.PathLike object, not NoneType

../../Library/miniconda3/lib/python3.6/posixpath.py:80: TypeError
```

<details>
<summary>conda list</summary>

```
# Name                    Version                   Build  Channel
absl-py                   0.2.2                      py_0    conda-forge
appnope                   0.1.0                    py36_0    conda-forge
asn1crypto                0.24.0                   py36_0    conda-forge
astor                     0.6.2                      py_0    conda-forge
atomicwrites              1.1.5                    py36_0    conda-forge
attrs                     18.1.0                     py_1    conda-forge
backcall                  0.1.0                      py_0    conda-forge
beautifulsoup4            4.6.0                    py36_0    conda-forge
bhmm                      0.6.3                    py36_1    conda-forge
blas                      1.0                         mkl  
bleach                    2.1.3                      py_0    conda-forge
blosc                     1.14.0                        1    conda-forge
bzip2                     1.0.6                         1    conda-forge
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.4.16                py36_0    conda-forge
cffi                      1.11.5                   py36_0    conda-forge
chardet                   3.0.4                    py36_0    conda-forge
clangdev                  6.0.0                 default_0    conda-forge
cloog                     0.18.1                        0  
conda                     4.5.8                    py36_0    conda-forge
conda-build               3.10.9                   py36_0    conda-forge
conda-env                 2.6.0                         0    conda-forge
conda-verify              2.0.0                    py36_0    conda-forge
cryptography              2.2.1                    py36_0    conda-forge
cycler                    0.10.0                   py36_0    conda-forge
cython                    0.28.3                   py36_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
deeptime                  0.1.4.dev15+g1b260f1           <pip>
dill                      0.2.7.1                  py36_0    conda-forge
entrypoints               0.2.3                    py36_1    conda-forge
filelock                  3.0.4                    py36_0    conda-forge
freetype                  2.8.1                         0    conda-forge
gast                      0.2.0                      py_0    conda-forge
glob2                     0.6                        py_0    conda-forge
gmp                       6.1.2                         0    conda-forge
grpcio                    1.12.0           py36hd9629dc_0  
h5py                      2.8.0            py36h470a237_0    conda-forge
hdf5                      1.10.1                        2    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
humanfriendly             4.12.1                     py_0    conda-forge
icu                       58.2                          0    conda-forge
idna                      2.6                      py36_1    conda-forge
intel-openmp              2018.0.3                      0  
ipykernel                 4.8.2                    py36_0    conda-forge
ipython                   6.4.0                    py36_0    conda-forge
ipython_genutils          0.2.0                    py36_0    conda-forge
ipywidgets                7.2.1                    py36_1    conda-forge
isl                       0.19                          0    conda-forge
jedi                      0.12.0                   py36_0    conda-forge
jinja2                    2.10                     py36_0    conda-forge
joblib                    0.11                     py36_0    conda-forge
jpeg                      9b                            2    conda-forge
jsonschema                2.6.0                    py36_1    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                    py36_0    conda-forge
jupyter_console           5.2.0                    py36_0    conda-forge
jupyter_contrib_core      0.3.3                    py36_1    conda-forge
jupyter_contrib_nbextensions 0.5.0                    py36_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.2.0                    py36_0    conda-forge
jupyter_latex_envs        1.4.4                    py36_0    conda-forge
jupyter_nbextensions_configurator 0.4.0                    py36_0    conda-forge
kiwisolver                1.0.1                    py36_1    conda-forge
libcxx                    6.0.0                         0    conda-forge
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1.20170329                  0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                          0    conda-forge
libpng                    1.6.34                        0    conda-forge
libprotobuf               3.5.2                         0    conda-forge
libsodium                 1.0.16                        0    conda-forge
libtiff                   4.0.9                         0    conda-forge
libxml2                   2.9.8                         0    conda-forge
libxslt                   1.1.32                        0    conda-forge
llvm-meta                 6.0.0                         0    conda-forge
llvmdev                   6.0.0                 default_3    conda-forge
llvmlite                  0.23.0                   py36_1    conda-forge
lxml                      4.2.1                    py36_0    conda-forge
markdown                  2.6.11                     py_0    conda-forge
markupsafe                1.0                      py36_0    conda-forge
matplotlib                2.2.2                    py36_1    conda-forge
mdtraj                    1.9.1                    py36_1    conda-forge
mistune                   0.8.3                    py36_1    conda-forge
mkl                       2018.0.3                      1  
mkl_fft                   1.0.2                    py36_0    conda-forge
mkl_random                1.0.1                    py36_0    conda-forge
mock                      2.0.0                    py36_0    conda-forge
more-itertools            4.2.0                      py_0    conda-forge
mpc                       1.1.0                         5    conda-forge
mpfr    [...]

2018-07-12 08:44 UTC, cwehmeyer commented
This need to change:

<details>
<summary>very long output</summary>

```
downloading data/pentapeptide-impl-solv.pdb: 8.00kB [00:00, 192kB/s]                    
downloading data/pentapeptide-00-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]


downloading data/pentapeptide-03-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]



downloading data/pentapeptide-04-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]




downloading data/pentapeptide-05-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]





downloading data/pentapeptide-06-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]






downloading data/pentapeptide-07-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]







downloading data/pentapeptide-08-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]








downloading data/pentapeptide-09-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]









downloading data/pentapeptide-10-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]










downloading data/pentapeptide-11-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]











downloading data/pentapeptide-12-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]












downloading data/pentapeptide-13-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]













downloading data/pentapeptide-14-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]














downloading data/pentapeptide-15-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]















downloading data/pentapeptide-16-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]
















downloading data/pentapeptide-17-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]

















downloading data/pentapeptide-18-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]


















downloading data/pentapeptide-19-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]



















downloading data/pentapeptide-20-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]




















downloading data/pentapeptide-21-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]





















downloading data/pentapeptide-22-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]






















downloading data/pentapeptide-23-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:00<?, ?B/s]























downloading data/pentapeptide-00-500ns-impl-solv.dcd: 5.77MB [00:03, 2.20MB/s]                            
downloading data/pentapeptide-01-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:03<?, ?B/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:   2%|▏         | 96.0k/5.76M [00:03<00:06, 921kB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:   4%|▍         | 256k/5.76M [00:03<00:05, 1.05MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:   7%|▋         | 432k/5.76M [00:03<00:04, 1.20MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  10%|█         | 600k/5.76M [00:03<00:04, 1.31MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  13%|█▎        | 776k/5.76M [00:03<00:03, 1.42MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  16%|█▋        | 960k/5.76M [00:03<00:03, 1.53MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  20%|█▉        | 1.12M/5.76M [00:04<00:02, 1.64MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  23%|██▎       | 1.30M/5.76M [00:04<00:02, 1.68MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  26%|██▋       | 1.52M/5.76M [00:04<00:02, 1.80MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  30%|██▉       | 1.72M/5.76M [00:04<00:02, 1.85MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  33%|███▎      | 1.93M/5.76M [00:04<00:02, 1.93MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  37%|███▋      | 2.13M/5.76M [00:04<00:01, 1.98MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  40%|████      | 2.33M/5.76M [00:04<00:01, 1.99MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  44%|████▍     | 2.54M/5.76M [00:04<00:01, 2.05MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  48%|████▊     | 2.75M/5.76M [00:04<00:01, 2.08MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  51%|█████▏    | 2.96M/5.76M [00:04<00:01, 2.07MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  55%|█████▌    | 3.18M/5.76M [00:05<00:01, 2.12MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  59%|█████▉    | 3.39M/5.76M [00:05<00:01, 2.14MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  63%|██████▎   | 3.62M/5.76M [00:05<00:01, 2.19MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  66%|██████▋   | 3.83M/5.76M [00:05<00:00, 2.18MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  70%|███████   | 4.04M/5.76M [00:05<00:00, 2.17MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  74%|███████▍  | 4.26M/5.76M [00:05<00:00, 2.19MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  78%|███████▊  | 4.48M/5.76M [00:05<00:00, 2.21MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  82%|████████▏ | 4.71M/5.76M [00:05<00:00, 2.26MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  86%|████████▌ | 4.93M/5.76M [00:05<00:00, 2.25MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  89%|████████▉ | 5.15M/5.76M [00:05<00:00, 2.23MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  94%|█████████▎| 5.39M/5.76M [00:06<00:00, 2.30MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd:  97%|█████████▋| 5.62M/5.76M [00:06<00:00, 2.29MB/s]
downloading data/pentapeptide-01-500ns-impl-solv.dcd: 5.77MB [00:06, 2.29MB/s]                            

downloading data/pentapeptide-02-500ns-impl-solv.dcd:   0%|          | 0.00/5.76M [00:06<?, ?B/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:   2%|▏         | 144k/5.76M [00:06<00:04, 1.44MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:   5%|▌         | 304k/5.76M [00:06<00:03, 1.50MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:   8%|▊         | 472k/5.76M [00:06<00:03, 1.55MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:  11%|█         | 648k/5.76M [00:06<00:03, 1.57MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:  13%|█▎        | 776k/5.76M [00:06<00:03, 1.37MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:  16%|█▋        | 960k/5.76M [00:06<00:03, 1.46MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:  20%|█▉        | 1.13M/5.76M [00:07<00:03, 1.59MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:  23%|██▎       | 1.33M/5.76M [00:07<00:02, 1.70MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:  26%|██▋       | 1.52M/5.76M [00:07<00:02, 1.79MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:  29%|██▉       | 1.70M/5.76M [00:07<00:02, 1.69MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:  33%|███▎      | 1.91M/5.76M [00:07<00:02, 1.83MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:  37%|███▋      | 2.12M/5.76M [00:07<00:02, 1.88MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:  40%|████      | 2.32M/5.76M [00:07<00:01, 1.95MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:  44%|████▍     | 2.52M/5.76M [00:07<00:01, 1.99MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:  47%|████▋     | 2.73M/5.76M [00:07<00:01, 1.98MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:  51%|█████     | 2.95M/5.76M [00:07<00:01, 2.05MB/s]

downloading data/pentapeptide-02-500ns-impl-solv.dcd:  55%|█████▍    | 3.15M/5.76M [00 [...]

2018-07-12 08:51 UTC, marscher commented
how did you generate your super long output? which terminal did you use?

2018-07-12 08:54 UTC, cwehmeyer commented
I just installed your PR and ran the first two cells in the 00-showcase notebook.

2018-07-12 08:57 UTC, marscher commented
I see, I only tested it on console. I guess I will use my progress_reporter package instead, as it handles notebooks as well.

2018-07-12 09:37 UTC, marscher commented
what is the intention of passing None as working_directory in the failing test?

2018-07-12 09:39 UTC, cwehmeyer commented
> what is the intention of passing None as working_directory in the failing test?

`working_directory=None` downloads the file to a temporary location. Do you consider this feature useful?

2018-07-12 11:55 UTC, marscher commented
It is useful, if one knows where the files are ending up - or are they just downloaded and discarded? If the latter is the case it would come to my mind that this is just a testing feature.

2018-07-12 13:04 UTC, cwehmeyer commented
`mdshare.fetch()` returns the path to the downloaded file.

2018-07-12 13:33 UTC, cwehmeyer requested changes

2018-07-12 13:33 UTC, cwehmeyer commented on mdshare/mdshare.py
> +                                          tqdm_args={'unit':'B'}, stage=i)
Here's another problem on my machine:

<details>
<summary>example</summary>

```Python
import mdshare

print(mdshare.__version__)

pdb = mdshare.fetch('pentapeptide-impl-solv.pdb', working_directory='data')
files = mdshare.fetch('pentapeptide-*-500ns-impl-solv.dcd', working_directory='data')

print(pdb)
print(files)
```

</details>

<details>
<summary>Traceback</summary>

```Python-Traceback
0.3.3.dev2+g6afef3e
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-f14cc035ec11> in <module>()
      3 print(mdshare.__version__)
      4 
----> 5 pdb = mdshare.fetch('pentapeptide-impl-solv.pdb', working_directory='data')
      6 files = mdshare.fetch('pentapeptide-*-500ns-impl-solv.dcd', working_directory='data')
      7 

~/git/mdshare/mdshare/mdshare.py in fetch(filename_pattern, working_directory, repository, max_attempts, delay, blur, callbacks, show_progress)
    182                 else:
    183                     pg._progress_register(size, description='downloading {}'.format(f),
--> 184                                           tqdm_args={'unit':'B'}, stage=i)
    185                     callbacks.append(partial(update, stage=i))
    186         files = [f for f, size in files]

TypeError: _progress_register() got an unexpected keyword argument 'tqdm_args'
```

</details>

2018-07-12 15:02 UTC, marscher commented
mhm your version of progress_reporter is out of data. I think it would
be easiest to depend on it.

2018-07-12 15:30 UTC, cwehmeyer commented
Much better, thanks!

But there is still an issue:

<img width="990" alt="image" src="https://user-images.githubusercontent.com/5278589/42643297-16396334-85f9-11e8-9349-cad0ea8019ba.png">

2018-08-15 15:26 UTC, cwehmeyer approved these changes

2018-08-15 15:27 UTC, merged